org: yandeveloper

service: manager-reports

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
