org: yandeveloper

service: manager-reports

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: !GetAtt CustomersTable.Arn

package:
  individually: true

resources:
  Resources:
    CustomersTable:
       Type: AWS::DynamoDB::Table
       Properties:
        TableName: CustomersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    ReportQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ReportQueue
        # Long polling, used to reduce the numbers of avoid requests
        ReceiveMessageWaitTimeSeconds: 20
        # This property going avoid that consumers got the same message, 180s can be too much (think about)
        VisibilityTimeout: 180
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ReportDLQ.Arn
          maxReceiveCount: 2

    ReportDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ReportDLQ
        MessageRetentionPeriod: 1209600 # that means 14 days, the maximun available to aws

build:
  esbuild:
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  populateDB:
    handler: src/functions/populateDB.handler
    timeout: 29
    events:
      - httpApi:
          path: /populate
          method: post
