org: yandeveloper

service: manager-reports

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: !GetAtt CustomersTable.Arn

package:
  individually: true

resources:
  Resources:
    CustomersTable:
       Type: AWS::DynamoDB::Table
       Properties:
        TableName: CustomersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

build:
  esbuild:
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  populateDB:
    handler: src/functions/populateDB.handler
    timeout: 23
    events:
      - httpApi:
          path: /populate
          method: post
